### ISSUE TITLE
Bug in "ns" precision when updating influxDB with string format of time

### ISSUE THREAD

**Issue by xinlongxu** [influxdata/influxdb-python#667] opened 2018-12-19 10:58 UTC
Floating point calculation cause difference record when updating with string format of time.

"2018-12-19T05:33:59.999Z" is the raw time of string format
"2018-12-19T05:33:59.999000064Z" is the new time record when updating with the above time, but insert a new record

![image](https://user-images.githubusercontent.com/8731696/50214957-9e88a100-03bc-11e9-95ff-e996f4fa24bc.png)

That happened becouse of the floating point calculation in  line_protocal.py

```
def _convert_timestamp(timestamp, precision=None):
    if isinstance(timestamp, Integral):
        return timestamp  # assume precision is correct if timestamp is int

    if isinstance(_get_unicode(timestamp), text_type):
        timestamp = parse(timestamp)

    if isinstance(timestamp, datetime):
        if not timestamp.tzinfo:
            timestamp = UTC.localize(timestamp)
```
        ns = (timestamp - EPOCH).total_seconds() * 1e9
```
        if precision is None or precision == 'n':
            return ns
        elif precision == 'u':
            return ns / 1e3
        elif precision == 'ms':
            return ns / 1e6
        elif precision == 's':
            return ns / 1e9
        elif precision == 'm':
            return ns / 1e9 / 60
        elif precision == 'h':
            return ns / 1e9 / 3600

    raise ValueError(timestamp)
```

![image](https://user-images.githubusercontent.com/8731696/50214635-c297b280-03bb-11e9-826b-70819911eb23.png)

**Comment by clslgrnc** [comment] 2019-02-15 17:44
Duplicate of #649?

**Comment by xginn8** [comment] 2019-04-07 14:44
Closing as duplicate of #649

**Closed by xginn8** 2019-04-07 14:44 UTC
