### ISSUE TITLE
Different Timestamps after uploading pandas Dataframe in InfluxDB

### ISSUE THREAD

**Issue by tomkrag** [influxdata/influxdb-python#412] opened 2017-02-07 09:42 UTC
Hi all,

I got different times displayed after uploading a pandas dataframe using the DataFrameClient. I have UNIX timestamps, which are convertet to DatetimeIndex. The python output displays proper times (in UTC). InfluxDB converts it to non readable timestamps.

Example:
**My Input (Unix) --> python output (UTC) --> InfluxDB output
1371215423523845000 --> 2013-06-14 13:10:23.523845 --> -1515392120**

--------------------------------

My code:

```
a=[1371215423523845000, 1371215500149460000]

df = pd.DataFrame(a)
df = pd.DatetimeIndex(a)

content= [(11, 22, "XXX"), (33, 44, "YYY")]
label= ["field1", "field2", "tag1"]

df= pd.DataFrame(content, columns=label, index=df)

client = DataFrameClient(host='localhost',port=8086, username = 'pi',password = 'raspberry', database = "MSKX2", timeout=None)

client.write_points(df,measurement="MSKTest12")
```

**Comment by gsokoll** [comment] 2017-03-03 07:01
I am having the same problem, using basically the examples/tutorial_pandas.py code.  Anyone have a suggested solution or workaround ?

This code:
```
import pandas as pd
from influxdb import DataFrameClient

host = 'localhost'
port = 8086
user = 'root'
password = 'root'
dbname = 'example'

client = DataFrameClient(host, port, user, password, dbname)
df = pd.DataFrame(data=list(range(10)), index=pd.date_range(start='2014-11-16', periods=10, freq='H'))
client.write_points(df, 'demo')

```
produces this dataframe
```
> df
                     0
2014-11-16 00:00:00  0
2014-11-16 01:00:00  1
2014-11-16 02:00:00  2
2014-11-16 03:00:00  3
2014-11-16 04:00:00  4
2014-11-16 05:00:00  5
2014-11-16 06:00:00  6
2014-11-16 07:00:00  7
2014-11-16 08:00:00  8
2014-11-16 09:00:00  9

```
but this output from InfluxDB CLI
```
> select * from demo
name: demo
time        0
----        -
-1991557120 2
-1382088704 8
-1174151168 3
-564682752  9
-356745216  4
460660736   5
668598272   0
1278066688  6
1486004224  1
2095472640  7

```

Clearly the timestamps are very broken.

**Comment by nirvana1122** [comment] 2017-03-06 15:02
Any resolution of this issue? I am facing similar problem.

**Comment by nirvana1122** [comment] 2017-03-06 17:15
Okay. So I found the problem. This could quite possibly Pandas issue. The problem is in _convert_dataframe_to_lines function. The problem can be fixed by changing 

 time = ((pd.to_datetime(dataframe.index).values.astype(int) /
                     precision_factor).astype(int).astype(str))

to 
time = ((pd.to_datetime(dataframe.index).astype(int) /
                     precision_factor).astype(int).astype(str))

Or by using protocol='json' in client.write_points call.

**Closed** 2017-03-08 16:53 UTC

**Comment by kaiseu** [comment] 2017-09-14 08:39
encountered the same issue, why not merge above resolution.

**Comment by Heiner92** [comment] 2018-06-05 15:02
I encoutered the same problem for DatetimeIndex. Fixed it like this:

```
if isinstance(dataframe.index, pd.tseries.index.DatetimeIndex):
    time = (dataframe.index.values.astype("int64") / precision_factor).astype(int).astype(str)
```

**Comment by stef30360** [comment] 2018-07-06 05:35
hi, @nirvana1122 
thanks ! but where and how change 👍 
time = ((pd.to_datetime(dataframe.index).values.astype(int) /
precision_factor).astype(int).astype(str))

to
time = ((pd.to_datetime(dataframe.index).astype(int) /
precision_factor).astype(int).astype(str))
  stef
