### ISSUE TITLE
Filtering by tags results in empty list

### ISSUE THREAD

**Issue by MHLG** [influxdata/influxdb-python#506] opened 2017-09-23 19:17 UTC
I'm observing an unexpected issue while reading data from InfluxDB

```
client = InfluxDBClient('localhost', 8086, 'root', 'root', 'influx_demo')

result = client.query("SELECT * FROM energy WHERE time >= '2015-01-01T00:00:00Z' AND time <= '2015-01-01T00:30:00Z'")

series = list(result.get_points(tags={'source': 'SBERA0'}))
```
series variable is an empty list and it should not; the same query using CLI returns the following points where [account location  source] are "Tags" and value is "Field"
```
> SELECT * FROM energy WHERE time >= '2015-01-01T00:00:00Z' AND time <= '2015-01-01T00:30:00Z'
name: energy
time                account location source value
----                ------- -------- ------ -----
1420070400000000000 BER     A        SBERA0 1
1420070400000000000 PAR     A        SPARA0 3
1420070400000000000 LOS     A        SLOSA0 6
1420070400000000000 LON     A        SLONA0 4
1420070400000000000 MIL     A        SMILA0 4
1420070700000000000 LON     A        SLONA0 6
1420070700000000000 MIL     A        SMILA0 8
[...]
```

I can make it work by using GROUP BY clause
```
result = client.query("SELECT * FROM energy WHERE time >= '2015-01-01T00:00:00Z' AND time <= '2015-01-01T00:30:00Z' GROUP BY source")

series = list(result.get_points(tags={'source': 'SBERA0'}))
```
But at this point I can only use the tag you have used in GROUP BY tags={'source': <value>} 
and using  multiple tags  tags={'source': <value>, 'location': <value>} is not returning appropriate values.

**Comment by xginn8** [comment] 2017-10-03 00:55
closing as a dupe of #251 and #441

**Closed by xginn8** 2017-10-03 00:55 UTC
