### ISSUE TITLE
dict.keys() returns `dict_keys` object and not a list in python 3

### ISSUE THREAD

**Issue by n4cr** [influxdata/influxdb-python#535] opened 2017-11-07 12:49 UTC
In the following example:

```python
class CandleSeriesHelper(SeriesHelper):
    """Instantiate SeriesHelper to write points to the backend."""

    class Meta:
        """Meta class stores time series helper configuration."""

        # The client should be an instance of InfluxDBClient.
        client = influx_client

        # The series name must be a string. Add dependent fields/tags
        # in curly brackets.
        series_name = 'candles.{exchange}.{pair}.{step}'

        # Defines all the fields in this time series.
        fields = ['open', 'close', 'high', 'low', 'volume', 'average', 'base_volume']

        # Defines all the tags for the series.
        tags = ['pair', 'exchange', 'step']

        # Defines the number of data points to store prior to writing
        # on the wire.
        bulk_size = 20000

        # autocommit must be set to True when using bulk_size
        autocommit = True

```

If you call it like `CandleSeriesHelper(**candle)` then you get an error:

```
../lib/python3.6/site-packages/influxdb/helper.py", line 120, in __init__
    kw.keys()))
NameError: Expected ['average', 'base_volume', 'close', 'exchange', 'high', 'low', 'open', 'pair', 'step', 'volume'], got dict_keys(['exchange', 'pair', 'open', 'close', 'low', 'high']).
```
It happens on the following line and its becuase in python 3 `dict.keys` does not return a list but a dict_keys object. 

https://github.com/influxdata/influxdb-python/blob/9d6de133053465fb5a4973be2bfc46cd6e4a88af/influxdb/helper.py#L114

**Comment by thiagofigueiro** [comment] 2017-12-10 20:52
@n4cr I believe this is fixed in version 5.0.0 because it now uses a set:

https://github.com/influxdata/influxdb-python/blob/v5.0.0/influxdb/helper.py#L116

**Comment by xginn8** [comment] 2017-12-11 13:51
This issue is fixed in the latest release, I've confirmed locally.

**Closed by xginn8** 2017-12-11 13:51 UTC

**Comment by aynesss** [comment] 2020-02-18 20:21
Can you give us solution for this issue after closed it .. thanks
