### ISSUE TITLE
influxdb-python client not working for Telegraf v1.3.2

### ISSUE THREAD

**Issue by danyli78** [influxdata/influxdb-python#472] opened 2017-06-21 22:29 UTC
OS: RedHat 7.2
Python: 2.7.5
InfluxDB-Python: v4.1.1 (https://github.com/influxdata/influxdb-python)
Telegraf: 1.3.2

Basically this is script that send a datapoint using the influxdb-python client to Telegraf port 8186 (HTTP)

[root@ip-***** ~]# ./test.py
InfluxDBClientError = 400: {"error":"http: bad request"}

When testing using the same script sending to Telegraf v1.2.1, it works fine without any error.

**Comment by sebito91** [comment] 2017-06-21 23:56
Duplicate of #467

**Comment by sebito91** [comment] 2017-07-06 04:33
@danyli78 are you still having trouble with writing points? Did you try out the recommendations on #467?

**Closed** 2017-09-29 02:12 UTC
