### ISSUE TITLE
tags in function get_points doesn't work correctly

### ISSUE THREAD

**Issue by nuaays** [influxdata/influxdb-python#441] opened 2017-04-26 07:31 UTC
when i used influxdb-python to query with tags as follows, the result showed nothing
```
result = client.query('select * from cpu limit 100;')
for p in list(result.get_points( measurement='cpu', tags={"host":"10.12.0.99"} )):
      print p
```

so, i checked the function of get_points and the function _tag_matches, then i found two errors in get_points
 
* 1.change serie.get('`tags`', {}) to serie.get('`columns`', {}) 
* 2.move condition judgement line which invoke _tag_matches  into for loop, and change `serie_tags` to `item`

please check the following change I made, and then the code works correctly
```
 -                serie_tags = serie.get('tags', {})
 -                if tags is None or self._tag_matches(serie_tags, tags):
 -                    for item in self._get_points_for_serie(serie):
 +                serie_tags = serie.get('columns', {})
 +                for item in self._get_points_for_serie(serie):
 +                    if tags is None or self._tag_matches(item, tags):   
```

**Comment by halmartin** [comment] 2017-04-28 15:04
@nuaays I think this is the same issue as https://github.com/influxdata/influxdb-python/issues/251

But maybe you can submit as a PR & it will be fixed? :smile:

**Comment by alexlep** [comment] 2017-05-02 22:49
Hi,
Faced the same issue, and the fix by **nuaays** doesn't fix the problem (at least in my case).
After checking the code it looks that in case we are using **tags** parameter for **get_points**, at first all the points are fetched from the DB and then one by one are compared to tags in provided parameter. Once the point corresponds to the value of the tag - it's added to generator.

I'm new to InfluxDB, so please correct me if I'm wrong, but it looks not efficient.
It's better to modify initial query, so the tag will be included in request. Tags are indexed, so such approach will work much faster.

So instead of
`result = client.query('select * from cpu limit 100;')`
the one should modify query to smth like:
`result = client.query('select * from cpu where host=\'{}\' limit 100;'.format(ip))`

**Comment by halmartin** [comment] 2017-05-03 09:13
> It's better to modify initial query, so the tag will be included in request. Tags are indexed, so such approach will work much faster.

This is what I ended up doing. Instead of using a generic query in `client.query()` you apply the tags to the initial query using `"".format()` and then get the results with `result.get_points()`

Perhaps the best solution then isn't to fix `get_points()` to properly parse tags, but to change the behaviour of `query()` to accept a dictionary of tags, which are then appended to the query before sending to InfluxDB?

As you pointed out, this will be more efficient since InfluxDB indexes tags.

**Comment by osyrisdc** [comment] 2017-08-24 10:41
Can you clarify the syntax for querying by tag? There is no mention of "".format() in any of the documentation.

**Comment by halmartin** [comment] 2017-08-28 12:18
@osyrisdc I am using the same workaround that @alexlep posted above. Apply the filters to the query before executing.

`result = client.query('select * from cpu where host=\'{}\' limit 100;'.format(ip))`

This allows InfluxDB to do the filtering and only return the relevant rows. The previous method (which also doesn't work) would select all the data and then filter on the client side in python. This is both slower and less efficient (Go versus Python).

**Comment by xginn8** [comment] 2017-10-03 00:56
closing as a dupe of #251

**Closed by xginn8** 2017-10-03 00:56 UTC
