### ISSUE TITLE
Writes failed with error

### ISSUE THREAD

**Issue by gopisera** [influxdata/influxdb-python#516] opened 2017-10-15 16:15 UTC
I'm trying to insert bunch of records (json  format) using  write_points but fails with the below error.

Traceback (most recent call last):
  File "influxload.py", line 56, in <module>
    client.write_points(json_body)
  File "/usr/lib/python2.7/site-packages/influxdb-4.1.1-py2.7.egg/influxdb/client.py", line 456, in write_points
    tags=tags, protocol=protocol)
  File "/usr/lib/python2.7/site-packages/influxdb-4.1.1-py2.7.egg/influxdb/client.py", line 506, in _write_points
    protocol=protocol
  File "/usr/lib/python2.7/site-packages/influxdb-4.1.1-py2.7.egg/influxdb/client.py", line 292, in write
    data = make_lines(data, precision).encode('utf-8')
  File "/usr/lib/python2.7/site-packages/influxdb-4.1.1-py2.7.egg/influxdb/line_protocol.py", line 126, in make_lines
    point.get('measurement', data.get('measurement'))
AttributeError: 'str' object has no attribute 'get'
You have new mail in /var/spool/mail/root

Regards,
Ramesh G

**Comment by xginn8** [comment] 2017-10-30 12:30
Is the variable `json_body` formatted properly (like the example here: https://influxdb-python.readthedocs.io/en/latest/include-readme.html#examples)?

**Comment by wolfohyeah** [comment] 2017-11-24 01:15
@xginn8 @gopisera  Hi , I'm a new learner of python and I have the same problem with @gopisera when using json to write points into the measurement. And I find that it will not have problem if the json has only one object like below:
`json_body = [
        {
          "measurement": perf,
              "tags": {
                  "host": hostname
                  },
              "fields": {
                  "cpu" : cpu_usage,
                  "mem" : mem_usage
              }
          }
        ]`
If the json has more than one objects like below, it will have the problem as @gopisera . In this case I have to traverse the json_body 'array' and use client.write_points for each member of the 'array', which means that I need to invoke the client.write_point for many times for the json. Since I prefer to use 'one write operation' to write 10 points to the influxdb, instead of '10 write operation and each write operation write one point', I give up the json and client.write_point and will use the curl to post all points to the influxdb in one time(to decrease the write operation to influxdb) as I did in my perl script.  
`json_body = [
        {
          "measurement": perf,
              "tags": {
                  "host": hostname
                  },
              "fields": {
                  "cpu" : cpu_usage,
                  "mem" : mem_usage
              }
          },
        {
          "measurement": perf,
              "tags": {
                  "host": hostname2
                  },
              "fields": {
                  "cpu" : cpu_usage2,
                  "mem" : mem_usage2
              }
          }
        ]`

**Comment by xginn8** [comment] 2017-11-25 17:04
I can't reproduce this issue in the latest release. In my testing, multiple points per one write works just fine. Can you either paste something showing exactly the error, or retry with the latest release? @wolfohyeah

**Comment by wolfohyeah** [comment] 2017-11-29 07:35
@xginn8  Hi, Thanks for your quick respond. I find out the reason of my problem today.  I misunderstood the [example](https://influxdb-python.readthedocs.io/en/latest/include-readme.html#examples) code. I thought that the '`json_body`' is a JSON object (instead of a Python object) so I invode `myjson=json.dumps(json_body)` before  `client.write_points`.  After I remove the `json.dumps` today, my script works well with several metric in one json_body[]. I think this is a python issue instead of influxdb-python. Sorry the above comment. 
@gopisera Not sure whether this comment is helpful for you.

**Comment by xginn8** [comment] 2017-11-30 01:40
Great, thanks for the update @wolfohyeah. Closing.

**Closed by xginn8** 2017-11-30 01:40 UTC

**Comment by thorsteinssonh** [comment] 2019-03-28 21:33
I had same misunderstanding of docs. The docs indicate with quotes that a json string is being passed to the write_points method.  I found that odd, but went with it and used json.dumps just like @wolfohyeah .  It's worth clarifying this first example in the docs, because its the absolute first thing we try with this library.  But many thanks for an excellent implementation. It's more pythonic by taking lists and dicts. Excellent work!

**Comment by RobinEccleston** [comment] 2019-04-09 16:35
I got this error, and ended up on this page through Google so wanted to share what my mistake was in the hope it helps someone else.

My problem was that I was passing a dict to client.write_points(), but it should have been a list of dicts. The solution to my issue was to make a list with a single item containing my dict, like so:

```
json_body=[json_body, ]
client.write_points(json_body)
```

**Comment by evilnick** [comment] 2019-04-20 02:59
The docs are rather misleading from a python perspective. Labelling an object 'json_body', when it is actually a standard python list doesn't help. Also, in the [tutorial](https://www.influxdata.com/blog/getting-started-python-influxdb/) it actually says:

" First, let’s add three points __in JSON format__ to a variable called json_body:" 

but again, it is actually a list object, not a JSON string.

**Comment by chromafunk** [comment] 2020-09-25 14:39
same here. I have just spent an hour to finally realize it wasn't a json object. Please change that on the docs
