### ISSUE TITLE
Make json decoder pluggable/ configurable

### ISSUE THREAD

**Issue by dschien** [influxdata/influxdb-python#313] opened 2016-04-04 20:10 UTC
Hi,

I would like to get Decimals back from my measurements values.
`simplejson` has an option `use_decimal=True` to achieve exactly that. 

If I could chose my json decode and pass kwargs to `get_points()` - that should be all I need.

Thanks

**Comment by aviau** [comment] 2016-04-04 20:45
duplicate of #272

**Closed by aviau** 2016-04-04 20:45 UTC
